### ISSUE TITLE
Allow to read public contents without login through API not working anymore?

### ISSUE THREAD

**Issue by donni106** [ikuseiGmbH/smart-village-app-humhub-ext#54]
There are errors when trying to fetch all calendar entries or posts from the new v2 controllers implemented with #19.

Calendar `GET /calendar`:

```
{
  "name": "Exception",
  "message": "Calling unknown method: humhub\\modules\\smartVillage\\controllers\\calendar\\CalendarController::handlePagination()",
  "code": 0,
  "type": "yii\\base\\UnknownMethodException",
  "file": "/var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Component.php",
  "line": 301,
  "stack-trace": [
  "#0 /var/www/localhost/htdocs/protected/humhub/modules/smart-village-app-humhub-ext/controllers/calendar/CalendarController.php(23): yii\\base\\Component->__call('handlePaginatio...', Array)",
  "#1 [internal function]: humhub\\modules\\smartVillage\\controllers\\calendar\\CalendarController->actionFind()",
  "#2 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)",
  "#3 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\\base\\InlineAction->runWithParams(Array)",
  "#4 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\\base\\Controller->runAction('find', Array)",
  "#5 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\\base\\Module->runAction('smartVillage/ca...', Array)",
  "#6 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\\web\\Application->handleRequest(Object(humhub\\components\\Request))",
  "#7 /var/www/localhost/htdocs/index.php(25): yii\\base\\Application->run()",
  "#8 {main}"
  ]
}
```

Calendar `GET /calendar/container/{id}` with id 5:

```
{
  "name": "Exception",
  "message": "Calling unknown method: humhub\\modules\\smartVillage\\controllers\\calendar\\CalendarController::handlePagination()",
  "code": 0,
  "type": "yii\\base\\UnknownMethodException",
  "file": "/var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Component.php",
  "line": 301,
  "stack-trace": [
  "#0 /var/www/localhost/htdocs/protected/humhub/modules/smart-village-app-humhub-ext/controllers/calendar/CalendarController.php(69): yii\\base\\Component->__call('handlePaginatio...', Array)",
  "#1 [internal function]: humhub\\modules\\smartVillage\\controllers\\calendar\\CalendarController->actionFindByContainer('5')",
  "#2 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)",
  "#3 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\\base\\InlineAction->runWithParams(Array)",
  "#4 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\\base\\Controller->runAction('find-by-contain...', Array)",
  "#5 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\\base\\Module->runAction('smartVillage/ca...', Array)",
  "#6 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\\web\\Application->handleRequest(Object(humhub\\components\\Request))",
  "#7 /var/www/localhost/htdocs/index.php(25): yii\\base\\Application->run()",
  "#8 {main}"
  ]
}
```

Post `GET /post`:

```
{
  "name": "Exception",
  "message": "Calling unknown method: humhub\\modules\\smartVillage\\controllers\\post\\PostController::handlePagination()",
  "code": 0,
  "type": "yii\\base\\UnknownMethodException",
  "file": "/var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Component.php",
  "line": 301,
  "stack-trace": [
  "#0 /var/www/localhost/htdocs/protected/humhub/modules/smart-village-app-humhub-ext/controllers/post/PostController.php(18): yii\\base\\Component->__call('handlePaginatio...', Array)",
  "#1 [internal function]: humhub\\modules\\smartVillage\\controllers\\post\\PostController->actionFind()",
  "#2 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)",
  "#3 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\\base\\InlineAction->runWithParams(Array)",
  "#4 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\\base\\Controller->runAction('find', Array)",
  "#5 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\\base\\Module->runAction('smartVillage/po...', Array)",
  "#6 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\\web\\Application->handleRequest(Object(humhub\\components\\Request))",
  "#7 /var/www/localhost/htdocs/index.php(25): yii\\base\\Application->run()",
  "#8 {main}"
  ]
}
```

Post `GET /post/container/{id}` with id 2:

```
{
  "name": "Exception",
  "message": "Calling unknown method: humhub\\modules\\smartVillage\\controllers\\post\\PostController::handlePagination()",
  "code": 0,
  "type": "yii\\base\\UnknownMethodException",
  "file": "/var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Component.php",
  "line": 301,
  "stack-trace": [
  "#0 /var/www/localhost/htdocs/protected/humhub/modules/smart-village-app-humhub-ext/controllers/post/PostController.php(59): yii\\base\\Component->__call('handlePaginatio...', Array)",
  "#1 [internal function]: humhub\\modules\\smartVillage\\controllers\\post\\PostController->actionFindByContainer('2')",
  "#2 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)",
  "#3 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\\base\\InlineAction->runWithParams(Array)",
  "#4 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\\base\\Controller->runAction('find-by-contain...', Array)",
  "#5 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\\base\\Module->runAction('smartVillage/po...', Array)",
  "#6 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\\web\\Application->handleRequest(Object(humhub\\components\\Request))",
  "#7 /var/www/localhost/htdocs/index.php(25): yii\\base\\Application->run()",
  "#8 {main}"
  ]
}
```

Please have an urgent look, thanks.

**Comment by gaurav-handysolver** [comment]
Okay @donni106
